"""add-timestamp-fields

Revision ID: 38a8c2ddb4b1
Revises: 4abe021db0b0
Create Date: 2026-02-04 19:58:50.596541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38a8c2ddb4b1'
down_revision: Union[str, Sequence[str], None] = '4abe021db0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_anamneses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation time'))
    op.add_column('base_anamneses', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Record update time'))
    op.add_column('child_anamneses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation time'))
    op.add_column('child_anamneses', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Record update time'))
    op.add_column('food_plans', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation time'))
    op.add_column('food_plans', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Record update time'))
    op.add_column('pacientes', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation time'))
    op.add_column('pacientes', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Record update time'))
    op.add_column('recordatory', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation time'))
    op.add_column('recordatory', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Record update time'))
    op.add_column('return_anamneses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation time'))
    op.add_column('return_anamneses', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Record update time'))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation time'))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Record update time'))
    op.add_column('workspace_invites', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Record update time'))
    op.alter_column('workspace_invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               server_default=sa.text('now()'),
               comment='Record creation time')
    op.add_column('workspace_members', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation time'))
    op.add_column('workspace_members', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Record update time'))
    op.add_column('workspaces', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Record update time'))
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               server_default=sa.text('now()'),
               comment='Record creation time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Record creation time')
    op.drop_column('workspaces', 'updated_at')
    op.drop_column('workspace_members', 'updated_at')
    op.drop_column('workspace_members', 'created_at')
    op.alter_column('workspace_invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Record creation time')
    op.drop_column('workspace_invites', 'updated_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('return_anamneses', 'updated_at')
    op.drop_column('return_anamneses', 'created_at')
    op.drop_column('recordatory', 'updated_at')
    op.drop_column('recordatory', 'created_at')
    op.drop_column('pacientes', 'updated_at')
    op.drop_column('pacientes', 'created_at')
    op.drop_column('food_plans', 'updated_at')
    op.drop_column('food_plans', 'created_at')
    op.drop_column('child_anamneses', 'updated_at')
    op.drop_column('child_anamneses', 'created_at')
    op.drop_column('base_anamneses', 'updated_at')
    op.drop_column('base_anamneses', 'created_at')
    # ### end Alembic commands ###
