"""add-scales-fields-bristol-hidric

Revision ID: 4abe021db0b0
Revises: ba824cf6adde
Create Date: 2026-02-01 13:05:26.280142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abe021db0b0'
down_revision: Union[str, Sequence[str], None] = 'ba824cf6adde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_anamneses', sa.Column('escala_bristol', sa.String(), nullable=True))
    op.add_column('base_anamneses', sa.Column('nivel_hidratacao', sa.String(), nullable=True))
    op.add_column('child_anamneses', sa.Column('escala_bristol', sa.String(), nullable=True))
    op.add_column('child_anamneses', sa.Column('nivel_hidratacao', sa.String(), nullable=True))
    op.add_column('return_anamneses', sa.Column('escala_bristol', sa.String(), nullable=True))
    op.add_column('return_anamneses', sa.Column('nivel_hidratacao', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_anamneses', 'nivel_hidratacao')
    op.drop_column('return_anamneses', 'escala_bristol')
    op.drop_column('child_anamneses', 'nivel_hidratacao')
    op.drop_column('child_anamneses', 'escala_bristol')
    op.drop_column('base_anamneses', 'nivel_hidratacao')
    op.drop_column('base_anamneses', 'escala_bristol')
    # ### end Alembic commands ###
