"""add-anamnese-sleep-fields

Revision ID: ba824cf6adde
Revises: d66c5daa8ae7
Create Date: 2026-01-30 21:04:56.221983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba824cf6adde'
down_revision: Union[str, Sequence[str], None] = 'd66c5daa8ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_anamneses', sa.Column('horario_dorme', sa.String(), nullable=True))
    op.add_column('base_anamneses', sa.Column('horario_acorda', sa.String(), nullable=True))
    op.add_column('base_anamneses', sa.Column('sono', sa.Enum('bom', 'mediano', 'ruim', name='sonoenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_anamneses', 'sono')
    op.drop_column('base_anamneses', 'horario_acorda')
    op.drop_column('base_anamneses', 'horario_dorme')
    # ### end Alembic commands ###
