"""add-recordatory-fields

Revision ID: d66c5daa8ae7
Revises: 2f6d85eeeebb
Create Date: 2026-01-30 16:31:52.151028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd66c5daa8ae7'
down_revision: Union[str, Sequence[str], None] = '2f6d85eeeebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordatory', sa.Column('outros', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordatory', 'outros')
    # ### end Alembic commands ###
